# Generated by Django 4.2.7 on 2023-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_category',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
