# Generated by Django 4.2.7 on 2023-12-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_contact_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Product_Image',
            new_name='Image',
        ),
    ]
