# Generated by Django 4.2.7 on 2023-12-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
