# Generated by Django 4.2.7 on 2023-12-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_products_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.registration')),
            ],
        ),
    ]
