# Generated by Django 4.2.7 on 2023-12-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_cart_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
