# Generated by Django 4.2.7 on 2023-12-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
