# Generated by Django 4.2.7 on 2023-12-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='cart_id',
        ),
    ]
