# Generated by Django 4.2.7 on 2023-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0006_rename_cart_order_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Pincode',
            field=models.CharField(max_length=9),
        ),
    ]
