# Generated by Django 4.2.7 on 2023-12-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0007_alter_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
