# Generated by Django 4.2.7 on 2023-12-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0008_remove_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
