# Generated by Django 4.2.7 on 2023-12-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0009_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Payment',
        ),
    ]
