# Generated by Django 4.2.7 on 2023-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
