# Generated by Django 4.2.7 on 2023-12-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0013_wishlist_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
